version: "3.3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d app_db" ]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    links:
      - postgres
    depends_on:
      - postgres
